version: "3.4"

services: 
  postgres:
    container_name: orm_crud
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: root
      
volumes:
  postgres_data: